export const radarListing = [
    {label: "ABERDEEN, SD", value: "ABR"},
    {label: "ALBANY, NY", value: "ALY"},
    {label: "ALBUQUERQUE, NM", value: "ABQ"},
    {label: "AMARILLO, TX", value: "AMA"},
    {label: "AUSTIN/SANANTONIO, TX", value: "EWX"},
    {label: "BINGHAMTON, NY", value: "BGM"},
    {label: "BIRMINGHAM, AL", value: "BMX"},
    {label: "BISMARCK, ND", value: "BIS"},
    {label: "BLACKSBURG/ROANOKE, VA", value: "RNK"},
    {label: "BOSTON /TAUNTON, MA", value: "BOX"},
    {label: "BROWNSVILLE, TX", value: "BRO"},
    {label: "BUFFALO, NY", value: "BUF"},
    {label: "BURLINGTON, VT", value: "BTV"},
    {label: "CARIBOU, ME", value: "CAR"},
    {label: "CHARLESTON, SC", value: "CHS"},
    {label: "CHARLESTON, WV", value: "RLX"},
    {label: "CHEYENNE, WY", value: "CYS"},
    {label: "CHICAGO, IL", value: "LOT"},
    {label: "CLEVELAND, OH", value: "CLE"},
    {label: "COLUMBIA, SC", value: "CAE"},
    {label: "CORPUS CHRISTI, TX", value: "CRP"},
    {label: "DALLAS / FT. WORTH, TX", value: "FWD"},
    {label: "DENVER/BOULDER, CO", value: "BOU"},
    {label: "DES MOINES, IA", value: "DMX"},
    {label: "DETROIT, MI", value: "DTX"},
    {label: "DODGE CITY, KS", value: "DDC"},
    {label: "DULUTH, MN", value: "DLH"},
    {label: "EL PASO, TX", value: "EPZ"},
    {label: "FARGO/GRAND FORKS, ND", value: "FGF"},
    {label: "GAYLORD/ALPENA, MI", value: "APX"},
    {label: "GOODLAND, KS", value: "GLD"},
    {label: "GRAND JUNCTION, CO", value: "GJT"},
    {label: "GRAND RAPIDS, MI", value: "GRR"},
    {label: "GREEN BAY, WI", value: "GRB"},
    {label: "GREER/GREENVILLE/SPRTBG, SC", value: "GSP"},
    {label: "HASTINGS, NE", value: "GID"},
    {label: "HOUSTON/ GALVESTON, TX", value: "HGX"},
    {label: "HUNTSVILLE, AL", value: "HUN"},
    {label: "INDIANAPOLIS, IN", value: "IND"},
    {label: "JACKSON, KY", value: "JKL"},
    {label: "JACKSON, MS", value: "JAN"},
    {label: "JACKSONVILLE, FL", value: "JAX"},
    {label: "KEY WEST, FL", value: "KEY"},
    {label: "LA CROSSE, WI", value: "ARX"},
    {label: "LAKE CHARLES, LA", value: "LCH"},
    {label: "LINCOLN/CENTRAL ILLINOIS, IL", value: "ILX"},
    {label: "LITTLE ROCK, AR", value: "LZK"},
    {label: "LOUISVILLE, KY", value: "LMK"},
    {label: "LUBBOCK, TX", value: "LUB"},
    {label: "MARQUETTE", value: "MQT"},
    {label: "MELBOURNE, FL", value: "MLB"},
    {label: "MEMPHIS, TN", value: "MEG"},
    {label: "MIAMI, FL", value: "MFL"},
    {label: "MIDLAND/ODESSA, TX", value: "MAF"},
    {label: "MILWAUKEE, WI", value: "MKX"},
    {label: "MINNEAPOLIS, MN", value: "MPX"},
    {label: "MOBILE, AL", value: "MOB"},
    {label: "MOREHEAD CITY, NC", value: "MHX"},
    {label: "MORRISTOWN/KNOXVILLE, TN", value: "MRX"},
    {label: "MT HOLLY/PHILADELPHIA, PA", value: "PHI"},
    {label: "N. WEBSTER/NORTHERN, IN", value: "IWX"},
    {label: "NASHVILLE, TN", value: "OHX"},
    {label: "NEW ORLEANS/SLIDELL, LA", value: "LIX"},
    {label: "NEW YORK CITY, NY", value: "OKX"},
    {label: "NORMAN, OK", value: "OUN"},
    {label: "NORTH PLATTE, NE", value: "LBF"},
    {label: "OMAHA, NE", value: "OAX"},
    {label: "PADUCAH, KY", value: "PAH"},
    {label: "PADUCAH, KY", value: "VWX"},
    {label: "PEACHTREE CITY/ATLANTA, GA", value: "FFC"},
    {label: "PITTSBURGH, PA", value: "PBZ"},
    {label: "PLEASANT HILL, MO", value: "EAX"},
    {label: "PORTLAND, ME", value: "GYX"},
    {label: "PUEBLO, CO", value: "PUB"},
    {label: "QUAD CITIES, IA", value: "DVN"},
    {label: "RALEIGH/DURHAM, NC", value: "RAH"},
    {label: "RAPID CITY, SD", value: "UNR"},
    {label: "RIVERTON, WY", value: "RIW"},
    {label: "SAN ANGELO, TX", value: "SJT"},
    {label: "SHREVEPORT, LA", value: "SHV"},
    {label: "SIOUX FALLS, IA", value: "FSD"},
    {label: "SPRINGFIELD, MO", value: "SGF"},
    {label: "ST. LOUIS, MO", value: "LSX"},
    {label: "STATE COLLEGE/CENTRAL, PA", value: "CTP"},
    {label: "STERLING, VA", value: "LWX"},
    {label: "TALLAHASSEE, FL", value: "TAE"},
    {label: "TAMPA BAY AREA, FL", value: "TBW"},
    {label: "TOPEKA, KS", value: "TOP"},
    {label: "TULSA, OK", value: "TSA"},
    {label: "WAKEFIELD, VA", value: "AKQ"},
    {label: "WICHITA, KS", value: "ICT"},
    {label: "WILMINGTON, NC", value: "ILM"},
    {label: "WILMINGTON/CINCINNATI, OH", value: "ILN"}
]