export const radarListing = [
    {label: "ABERDEEN, SD", value: "KABR"},
    {label: "ALBANY, NY", value: "KENX"},
    {label: "ALBUQUERQUE, NM", value: "KABX"},
    {label: "AMARILLO, TX", value: "KAMA"},
    {label: "AUSTIN/SANANTONIO, TX", value: "KEWX"},
    {label: "BINGHAMTON, NY", value: "KBGM"},
    {label: "BIRMINGHAM, AL", value: "KBMX"},
    {label: "BISMARCK, ND", value: "KMBX"},
    {label: "BLACKSBURG/ROANOKE, VA", value: "KFCX"},
    {label: "BOSTON /TAUNTON, MA", value: "KBOX"},
    {label: "BROWNSVILLE, TX", value: "KBRO"},
    {label: "BUFFALO, NY", value: "KBUF"},
    {label: "BURLINGTON, VT", value: "KCXX"},
    {label: "CARIBOU, ME", value: "KCBW"},
    {label: "CHARLESTON, SC", value: "KCLX"},
    {label: "CHARLESTON, WV", value: "KRLX"},
    {label: "CHEYENNE, WY", value: "KCYS"},
    {label: "CHICAGO, IL", value: "KLOT"},
    {label: "CLEVELAND, OH", value: "KCLE"},
    {label: "COLUMBIA, SC", value: "KCAE"},
    {label: "CORPUS CHRISTI, TX", value: "KCRP"},
    {label: "DALLAS / FT. WORTH, TX", value: "KFWS"},
    {label: "DENVER/BOULDER, CO", value: "KFTG"},
    {label: "DES MOINES, IA", value: "KDMX"},
    {label: "DETROIT, MI", value: "KDTX"},
    {label: "DODGE CITY, KS", value: "KDDC"},
    {label: "DULUTH, MN", value: "KDLH"},
    {label: "EL PASO, TX", value: "KEPZ"},
    {label: "FARGO/GRAND FORKS, ND", value: "KMVX"},
    {label: "GAYLORD/ALPENA, MI", value: "KAPX"},
    {label: "GOODLAND, KS", value: "KGLD"},
    {label: "GRAND JUNCTION, CO", value: "KGJT"},
    {label: "GRAND RAPIDS, MI", value: "KGRR"},
    {label: "GREEN BAY, WI", value: "KGRB"},
    {label: "GREER/GREENVILLE/SPRTBG, SC", value: "KGSP"},
    {label: "HASTINGS, NE", value: "KUEX"},
    {label: "HOUSTON/ GALVESTON, TX", value: "KHGX"},
    {label: "HUNTSVILLE, AL", value: "KHTX"},
    {label: "INDIANAPOLIS, IN", value: "KIND"},
    {label: "JACKSON, KY", value: "KJKL"},
    {label: "JACKSON, MS", value: "KDGX"},
    {label: "JACKSONVILLE, FL", value: "KVAX"},
    {label: "KEY WEST, FL", value: "KBYX"},
    {label: "LA CROSSE, WI", value: "KARX"},
    {label: "LAKE CHARLES, LA", value: "KLCH"},
    {label: "LINCOLN/CENTRAL ILLINOIS, IL", value: "KILX"},
    {label: "LITTLE ROCK, AR", value: "KLZK"},
    {label: "LOUISVILLE, KY", value: "KLVX"},
    {label: "LUBBOCK, TX", value: "KLBB"},
    {label: "MARQUETTE", value: "KMQT"},
    {label: "MELBOURNE, FL", value: "KMLB"},
    {label: "MEMPHIS, TN", value: "KNQA"},
    {label: "MIAMI, FL", value: "KAMX"},
    {label: "MIDLAND/ODESSA, TX", value: "KMAF"},
    {label: "MILWAUKEE, WI", value: "KMKX"},
    {label: "MINNEAPOLIS, MN", value: "KMPX"},
    {label: "MOBILE, AL", value: "KMOB"},
    {label: "MOREHEAD CITY, NC", value: "KMHX"},
    {label: "MORRISTOWN/KNOXVILLE, TN", value: "KMRX"},
    {label: "MT HOLLY/PHILADELPHIA, PA", value: "KDIX"},
    {label: "N. WEBSTER/NORTHERN, IN", value: "KIWX"},
    {label: "NASHVILLE, TN", value: "KOHX"},
    {label: "NEW ORLEANS/SLIDELL, LA", value: "KLIX"},
    {label: "NEW YORK CITY, NY", value: "KOKX"},
    {label: "NORMAN, OK", value: "KTLX"},
    {label: "NORTH PLATTE, NE", value: "KLNX"},
    {label: "OMAHA, NE", value: "KOAX"},
    {label: "PADUCAH, KY", value: "KPAH"},
    {label: "PADUCAH, KY", value: "KVWX"},
    {label: "PEACHTREE CITY/ATLANTA, GA", value: "KFFC"},
    {label: "PITTSBURGH, PA", value: "KPBZ"},
    {label: "PLEASANT HILL, MO", value: "KEAX"},
    {label: "PORTLAND, ME", value: "KGYX"},
    {label: "PUEBLO, CO", value: "KPUX"},
    {label: "QUAD CITIES, IA", value: "KDVN"},
    {label: "RALEIGH/DURHAM, NC", value: "KRAX"},
    {label: "RAPID CITY, SD", value: "KUDX"},
    {label: "RIVERTON, WY", value: "KRIW"},
    {label: "SAN ANGELO, TX", value: "KSJT"},
    {label: "SHREVEPORT, LA", value: "KSHV"},
    {label: "SIOUX FALLS, IA", value: "KFSD"},
    {label: "SPRINGFIELD, MO", value: "KSGF"},
    {label: "ST. LOUIS, MO", value: "KLSX"},
    {label: "STATE COLLEGE/CENTRAL, PA", value: "KCCX"},
    {label: "STERLING, VA", value: "KLWX"},
    {label: "TALLAHASSEE, FL", value: "KTLH"},
    {label: "TAMPA BAY AREA, FL", value: "KTBW"},
    {label: "TOPEKA, KS", value: "KTWX"},
    {label: "TULSA, OK", value: "KINX"},
    {label: "WAKEFIELD, VA", value: "KDOX"},
    {label: "WICHITA, KS", value: "KICT"},
    {label: "WILMINGTON, NC", value: "KLTX"},
    {label: "WILMINGTON/CINCINNATI, OH", value: "KILN"}
]